# Generated by Django 4.2.13 on 2024-07-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=8)),
                ('email', models.CharField(max_length=320)),
                ('password', models.CharField(max_length=132)),
            ],
        ),
    ]
